font-path: /usr/share/fonts/TTF/DejaVuSansMono.ttf
font-size: 18
grid-size: 40
grid-width: 6
grid-height: 4
edge-distance: 10

items:
- name: pulled-command
  command: [date, "+%a %e %l:%M:%S %p"]
  interval-sec: 1.0
  horizontal-padding: 10

- name: pushed-command
  interpreter: bash
  script: $DF_PYTHON $scr/panel/bspwm-workspaces.py
  trigger-show: true

- name: pulled-command
  interpreter: bash
  script: $scr/panel/battery.sh
  interval-sec: 60.0

- name: pushed-command
  interpreter: bash
  script: $scr/panel/volume.sh
  trigger-show: true

- name: pulled-command
  interpreter: bash
  script: "echo upd: $(yaourt -Qua | wc -l)"
  interval-sec: 60.0
